Update translation to v2.7.0
optuna/doc-optuna-zh-cn pull request #10
Opened 2021-05-07 00:14 UTC by chenghuzi

As titled.

Notice that main changes are two recently added tutorial translations. Some redundant comments are removed. 

Autogenerated parts are not included in this update though some of the autogenerated `.po` files are updated as the timestamps are changed.

2021-05-19 07:48 UTC, belldandyxtq requested changes

2021-05-19 07:48 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/tutorial/20_recipes/002_multi_objective.po
>  msgstr "本教程借由同时优化 PyTorch 编写的模型在 MNIST 数据集上的验证集准确度以及 FLOPS 来展示 Optuna 的多目标优化特性."
Fasion MNIST

2021-05-19 07:48 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/tutorial/20_recipes/009_ask_and_tell.po
> +"本教程展示了, 在三种情况下 ask-and-tell 接口是有益的."
本教程将展示三种可以用到ask-and-tell接口的情况

2021-05-19 07:48 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/tutorial/20_recipes/009_ask_and_tell.po
> +"需要不同于 ``trial`` 的额外参数, 你就需要顶一个类, 如同 `How to define objective functions that have own arguments? "
你就需要定义一个类，例如

2021-05-19 07:48 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/tutorial/20_recipes/009_ask_and_tell.po
> +msgstr "为了更快的优化, ask-and-tell 接口使我们可以优化一个批目标函数. 比如, 并行求值, 向量操作等."
为了更快地完成优化, ask-and-tell 接口支持优化批目标函数.

2021-05-19 07:48 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/tutorial/20_recipes/010_reuse_best_trial.po
> +msgstr "有时候, 在完成超参数优化以后, 你可能要用最佳的超参数对对目标函数重新求值."
有时候, 在完成超参数优化以后, 你可能要用最佳的超参数对~对~目标函数重新求值.

2021-05-19 07:50 UTC, belldandyxtq commented
Next time, can you please separate `files with translation update` and `files without translation update` into different PRs? So that we do not have a huge diff to look into and try to find the update. For those `files without translation update` we can just merge.

2021-05-19 07:52 UTC, belldandyxtq commented
And for those `needs translation update but will do in another PR`. Can you please include them when the translation is ready so that we do not forget

2021-05-28 00:17 UTC, chenghuzi commented on source/locale/zh_CN/LC_MESSAGES/tutorial/20_recipes/009_ask_and_tell.po
> +"需要不同于 ``trial`` 的额外参数, 你就需要顶一个类, 如同 `How to define objective functions that have own arguments? "
I think "就像...里做的那样" might be better

2021-05-31 04:40 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/tutorial/20_recipes/009_ask_and_tell.po
> +"需要不同于 ``trial`` 的额外参数, 你就需要顶一个类, 如同 `How to define objective functions that have own arguments? "
I was trying to point out a typo, "顶一个类"; I think your change is also OK

2021-05-31 15:31 UTC, belldandyxtq approved these changes

2021-06-01 17:50 UTC, merged