Translation of optuna.trial
optuna/doc-optuna-zh-cn pull request #15
Opened 2021-07-11 09:13 UTC by chenghuzi

2021-08-03 13:50 UTC, belldandyxtq requested changes

2021-08-03 13:50 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.trial.FixedTrial.po
> +msgstr "为每一个参数提供固定值 suggestion 的 trial 类."
为每一个参数提供唯一固定值的 trial 类.

2021-08-03 13:50 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.trial.FixedTrial.po
> +":class:`~optuna.trial.FixedTrial` 不依赖于 :class:`~optuna.study.Study`, 所以他对于部署优化结果是有用的."
所以能被用于部署优化结果.

2021-08-03 13:50 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.trial.FixedTrial.po
> +msgstr "细节和属性请参考 :class:`~optuna.trial.Trial`."
方法和属性的细节请参考

2021-08-03 13:50 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.trial.FrozenTrial.po
> +":class:`~optuna.trial.FrozenTrial` 不依赖于 :class:`~optuna.study.Study`, 所以他对于部署优化结果是有用的."
所以能被用于部署优化结果.

2021-08-03 13:50 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.trial.FrozenTrial.po
> +msgstr "属性通过 :func:`optuna.Study.optimize` 来设定, 但是其中一些属性可以在优化后被更新. "
Please see https://github.com/optuna/optuna/pull/2833

2021-08-03 13:50 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.trial.FrozenTrial.po
> +msgstr "细节和属性请参考 :class:`~optuna.trial.Trial`."
方法和属性的细节请参考

2021-08-03 13:50 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.trial.FrozenTrial.po
> +msgstr "每一个 :class:`~optuna.study.Study` 所有的独特和连续的 :class:`~optuna.trial.Trial` 数字. "
每一个 :class:`~optuna.study.Study` 所有的独特和连续的 :class:`~optuna.trial.Trial` 号.

2021-08-03 13:50 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.trial.FrozenTrial.po
> +msgstr "Trial 目标函数值的序列. 如果该问题为多目标优化, 则其长度大于1. 如果 ``state`` 是 ``None`` 或者 "
I do not see the part after "如果" in the original text

2021-08-03 13:50 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.trial.FrozenTrial.po
> +msgstr "Trial 步骤（例如, 神经网络训练的 epoch. "
missing ) at the end

2021-08-03 13:50 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.trial.Trial.po
> +"因此, 库用户并不关心该对象的实例化. "
因此, 库用户并不用关心该对象的实例化.

2021-08-03 13:50 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.trial.Trial.po
> +msgstr "Trial 步骤（例如, 神经网络训练的 epoch）. "
I don't think the first part matches the English

`目标函数的返回值`

2021-08-03 13:50 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.trial.Trial.po
> +msgstr "注意, optuna 在内部使用该方法来保存如 trial 失败之类的系统信息. 请使用"
... 保存如 trial 失败原因之类的系统信息.

2021-08-03 13:50 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.trial.Trial.po
> +msgstr "可以通过 :func:`optuna.trial.Trial.user_attrs` 访问试 trial 中的用户属性. "
访问~试~

2021-08-03 13:50 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.trial.Trial.po
> +"为 `SVC <https://scikit-"
missing translation before this
`该值从choices中取样`

2021-08-03 13:50 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.trial.Trial.po
> +msgstr "suggesttion 值."
suggestion

typo

2021-08-03 13:50 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.trial.Trial.po
> +":func:`~optuna.trial.Trial.suggest_loguniform` and "
and -> 和

2021-08-03 13:50 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.trial.Trial.po
> +msgstr "如果 ``step is not None`` 并且制定了 ``log = True``."
如果 ``step is not None`` 并且指定了 ``log = True``

2021-08-03 13:50 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.trial.Trial.po
> +msgstr "注意,  "
Missing translation at line 611?

2021-08-03 13:50 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.trial.Trial.po
> +"``step != 1`` 和 ``log`` 参数不能同时使用要把 "
参数不能同时使用。要把

2021-08-26 21:45 UTC, chenghuzi commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.trial.FixedTrial.po
> +msgstr "为每一个参数提供固定值 suggestion 的 trial 类."
Could it be "为每个参数都提供固定值的 trial 类."?

2021-08-26 21:54 UTC, chenghuzi commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.trial.Trial.po
> +msgstr "Trial 步骤（例如, 神经网络训练的 epoch）. "
I don't understand this part, why "目标函数的返回值" is here?

2021-08-26 21:59 UTC, chenghuzi commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.trial.Trial.po
> +msgstr "注意,  "
No this is reflected in line 629. Any translation here leads to crashed rendered HTML output.

2021-08-26 22:03 UTC, chenghuzi commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.trial.FrozenTrial.po
> +msgstr "属性通过 :func:`optuna.Study.optimize` 来设定, 但是其中一些属性可以在优化后被更新. "
Will finish this part once we update the original doc to the latest version.

2021-09-07 04:34 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.trial.Trial.po
> +msgstr "Trial 步骤（例如, 神经网络训练的 epoch）. "
I think the text has shifted somehow, the `目标函数的返回值` is the translation above at line 305

2021-10-15 02:11 UTC, belldandyxtq approved these changes

2021-10-15 02:11 UTC, merged