Translation of optuna.visualization
optuna/doc-optuna-zh-cn pull request #17
Opened 2021-08-06 01:16 UTC by chenghuzi

2021-08-12 15:26 UTC, belldandyxtq requested changes

2021-08-12 15:26 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.samplers.BaseSampler.po
> +"的实现, 请参考 :func:`~optuna.samplers.intersection_search_space`. "
```
请参考 :func:`~optuna.samplers.intersection_search_space`作为:func:`~optuna.samplers.BaseSampler.infer_relative_search_space`的范例
```
What do you think? I feel the old one is not nature to Chinese as it follows the English phrasing

2021-08-12 15:26 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.samplers.BaseSampler.po
> +"实例会被复制, 其中就报错了随机数生成器的状态, 因此它们可能会产生同样的 suggestion "
其中就包括了随机数生成器的状态

typo

2021-08-12 15:26 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.samplers.BaseSampler.po
> +"只有当参数不属于 :func:`~optuna.samplers.BaseSampler.sample_relative`"
该方法仅用于采样那些不属于 :func:`~optuna.samplers.BaseSampler.sample_relative`的参数

I think the old translation is a little confusing.

2021-08-12 15:26 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.samplers.BaseSampler.po
>  msgid "Name of the sampled parameter."
missing translation?

2021-08-12 15:26 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.samplers.CmaEsSampler.po
> +msgstr "一个包含了 CMA-ES 的初始参数的字典。在默认情况下，每个分布的 ``low`` and ``high`` 的平均数是被采用的。"
missing translation of the later half

2021-08-12 15:26 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.samplers.CmaEsSampler.po
> +"sampling.那些并不包含在相对搜索空间中的参数是通过这个 sampler "
sampling -> 采样
Since we translate other `sampling` in this paragraph

2021-08-12 15:26 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.samplers.CmaEsSampler.po
> +"一个 :class:`~optuna.samplers.BaseSampler`  实例，它用于独立 "
I think this part is a duplication of the paragraph above

2021-08-12 15:26 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.samplers.CmaEsSampler.po
> +"如果设置成 :obj:`None` "
ditto

2021-08-12 15:26 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.samplers.CmaEsSampler.po
> +":class:`optuna.samplers` 模块提供了内置的独立 sampler, 比如 "
ditto

2021-08-12 15:26 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.samplers.CmaEsSampler.po
> +"只有当参数不属于 :func:`~optuna.samplers.BaseSampler.sample_relative`"
ditto

2021-08-12 15:26 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/visualization/generated/optuna.visualization.plot_edf.po
> +msgstr "绘制的 EDF 假设ubiaohanshu在目标函数空间中是均匀分布的."
绘制EDF时假设目标函数在目标函数空间中是均匀分布的.

2021-08-12 15:26 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/visualization/generated/optuna.visualization.plot_param_importances.po
> +":class:`~optuna.importance._mean_decrease_impurity.MeanDecreaseImpurityImportanceEvaluator`."
The class is wrong

2021-08-12 15:26 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/visualization/generated/optuna.visualization.matplotlib.plot_param_importances.po
> +":class:`~optuna.importance._mean_decrease_impurity.MeanDecreaseImpurityImportanceEvaluator`."
The class is wrong

2021-08-12 15:26 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/visualization/generated/optuna.visualization.plot_pareto_front.po
> +msgstr "一个用于包含所有主要 trial 的目标函数值的选项."
设置该选项来包含所有主要 trial 的目标函数值

I think the old translation is confusing

2021-08-26 22:07 UTC, chenghuzi commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.samplers.BaseSampler.po
> +"的实现, 请参考 :func:`~optuna.samplers.intersection_search_space`. "
How about 

```
"请参考 :func:`~optuna.samplers.intersection_search_space`, 因为它是 "
":func:`~optuna.samplers.BaseSampler.infer_relative_search_space` "
"的一个实现."
```

2021-08-26 22:15 UTC, chenghuzi commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.samplers.CmaEsSampler.po
> +"一个 :class:`~optuna.samplers.BaseSampler`  实例，它用于独立 "
Yes line 133 = line 156 + line 170. But Sphinx generated this part, so I just copied and paste the translation from line 133 to other two lines.

2021-10-15 02:11 UTC, belldandyxtq approved these changes

2021-10-15 02:11 UTC, merged