Update the main doc to v2.10
optuna/doc-optuna-zh-cn pull request #18
Opened 2021-10-21 21:10 UTC by chenghuzi

* Update dependencies and the original doc to v2.10. 
* Update main doc translation, i.e., `*.po` files which are not under any `generated` folders to v2.10

2021-10-28 07:21 UTC, belldandyxtq requested changes
I have a few questions:
1. Did you include new translations in this PR, because I see some new translations. I thought this is just a auto-generated update PR.
2. I notice some Chinese in the `msgid`, Is this normal?

2021-10-28 07:21 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/cli.po
> +msgstr ""
missing translations?

2021-10-28 07:21 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/cli.po
> +msgstr "将多层的列展, 例如参数, 进行展平."
`将多层的嵌套列, 例如参数, 进行展平. `

2021-10-28 07:21 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/cli.po
> +msgstr ""
`最佳trial`

match the blow

2021-10-28 07:21 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/cli.po
> +msgstr "将多层的列, 例如参数和 user_attrs 展平."
将多层的嵌套列, 例如参数和 user_attrs 展平.

2021-10-28 07:21 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/cli.po
> +msgstr ""
ditto

2021-10-28 07:21 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/cli.po
> +msgstr "用于提取最佳 trial (那些位于帕累托前沿上的 trial) 的 study 名 "
`最佳 trial (那些位于帕累托前沿上的 trial) 的 study 名`

I think this is more nature

2021-10-28 07:21 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/cli.po
>  msgstr ""
missing translation

2021-10-28 07:21 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/cli.po
> +msgstr "使用 ask 命令来结束一个 trial."
结束一个 ask命令创建的trial.

2021-10-28 07:21 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/cli.po
> +msgstr "Trial 数."
Trial号

2021-10-28 07:21 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.copy_study.po
> +msgstr ""
missing

2021-10-28 07:21 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.copy_study.po
> +msgstr ""
missing

2021-10-28 07:21 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.copy_study.po
> +msgid "示例"
shouldn't we have English here?

2021-10-28 07:21 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.copy_study.po
> +msgid "参数"
ditto

2021-10-28 07:21 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.copy_study.po
> +msgstr ""
The translation and original test in this file are strange

2021-10-28 07:21 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.pruners.PatientPruner.po
> +msgid "示例"
ditto

2021-10-28 07:21 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.storages.RetryFailedTrialCallback.po
> +msgid "参数"
ditto

2021-10-28 07:21 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.storages.fail_stale_trials.po
> +msgid "参数"
ditto

2021-10-28 07:21 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.study.MaxTrialsCallback.po
> +msgid "示例"
ditto

2021-10-28 07:21 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.study.copy_study.po
> +msgid "示例"
ditto

2021-10-28 07:21 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.trial.Trial.po
> +"如果``log`` 是 true, 则在一开始的时候,  suggestion 值的范围会被分成宽度为 1 的网格点. 然后 suggestion"
Isn't this the same as line 667?

2021-10-28 07:21 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.trial.create_trial.po
> +msgid "``value`` or ``values``"
The English is broken?

2021-10-28 07:21 UTC, belldandyxtq commented on source/locale/zh_CN/LC_MESSAGES/reference/visualization/generated/optuna.visualization.matplotlib.plot_pareto_front.po
> +msgid "示例"
ditto

2021-11-04 13:36 UTC, chenghuzi commented on source/locale/zh_CN/LC_MESSAGES/reference/cli.po
> +msgstr ""
I guess this is an exact command option so probably we don't need to translate it

2021-11-04 13:53 UTC, chenghuzi commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.copy_study.po
> +msgid "示例"
This is generated automatically by the sphinx. Try searching some other keywords like "返回类型" and you will find more.

2021-11-04 13:56 UTC, chenghuzi commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.trial.Trial.po
> +"如果``log`` 是 true, 则在一开始的时候,  suggestion 值的范围会被分成宽度为 1 的网格点. 然后 suggestion"
This is the issue we discussed before: sometimes when you get a `note` in the original doc, you'll have two duplicating `msgid`s for them and the second one is the one that determines the translation.

2021-11-04 14:24 UTC, chenghuzi commented on source/locale/zh_CN/LC_MESSAGES/reference/generated/optuna.trial.create_trial.po
> +msgid "``value`` or ``values``"
Yes, due to the `#, fuzzy`. But now it's fixed.

2021-11-12 02:01 UTC, belldandyxtq approved these changes

2021-11-12 02:01 UTC, merged